services:

  vote:
    image: trevorjsmith/vote:latest
    ports:
      - 5000:80

  result:
    image: trevorjsmith/result:latest
    ports:
      - 5001:80

  worker:
    image: trevorjsmith/worker:latest

